apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: opentelemetry-operator
      version: '0.32.0'
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  values: {}
