---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: opentelemetry
spec:
  interval: 5m
  # dependsOn:
  #   - name: cert-manager
  chart:
    spec:
      chart: opentelemetry-operator
      version: "0.32.0"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3