apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-operator
spec:
  interval: 1m
  chart:
    spec:
      chart: opentelemetry-operator
      version: '0.32.0'
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: opentelemetry
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
