apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: jetstack/cert-manager
      version: 'v1.12.2'
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 1m