---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 10m0s
  provider: generic
  timeout: 3m0s
  url: https://charts.jetstack.io